site_name: Kenzy Louis
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: lime

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/kenzylouis
  - icon: fontawesome/brands/twitter
    link: https://x.com/kenzylouis1
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/kenzy-louis-0b643a3a

markdown_extensions: 
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences

copyright: |
  &copy; 2024 <a href="https://github.com/kenzylouis" target="_blank">Kenzy Louis</a>